#!/bin/bash
#
#	cifrado y descifrado de mensajes y archivos
#	creacion de esteganografías y mensajes cifrados en QR
#	proxy de IRC cifrado con GPG (con clave)
#	bufandarosa - versión 0.1.4 (fauno2)
#	Licencia AGPL
#

# --------------------------- funciones ---------------------------------

function uno {
	[ "$1" == "-h" ]&& echo 'elige un elemento de una lista, ejemplo: echo "a b c d" | uno ' && exit
	# elije uno al azar de una lista
        LISTA="`cat /dev/stdin | tr ' ' "\n"`"
        N=`echo "$LISTA" | wc -l`
        echo "$LISTA" | sed -n $[$RANDOM%$N+1]p
}
function metadatos {
	[ "$1" == "-h" ]&& echo 'borra los metadatos de un archivo, ejemplo: metadatos archivo.jpg ' && exit
	convert -strip "$1" "$1"
}
function borrar {
	[ "$1" == "-h" ]&& echo 'borra un archivo (para simple), ejemplo: ' && exit
	shred -uz -n 10 "$1"
}
function nombre {
	[ "$1" == "-h" ]&& echo 'genera nombres al azar' && exit
	pwgen -1 $[$RANDOM%6+5]
}
function paste {
	[ "$1" == "-h" ]&& echo 'envia un mensaje a un paste al azar usando tor, ejemplo: `echo "hola" | paste`' && exit
	publicar
}
function tinyurl {
	[ "$1" == "-h" ]&& echo 'publica un archivo o mensaje en tinyurl (tiene espacio limitado), ejemplo: echo "hola" | tinyurl ' && exit
	[ "$1" == "" ] && BASE64=`cat /dev/stdin | base64 -w0`|| BASE64="$1"
	MIME=`echo $BASE64 | base64 -d | file -i - | cut -d" " -f2 | sed 's/;//'`
	descarga "https://tinyurl.com/create.php?url=data:$MIME;charset=utf-8;base64,$BASE64" \
	| grep -o "https\?://[^\"']\+" | sed 's/[<|\ ].*$//g' | grep "//tinyurl.com/..*" |  sort -u
}
function publicar {
	[ "$1" == "-h" ]&& echo 'envia un archivo a un servidor de archivos al azar usando tor, ejemplo: `publicar imagen.png uploadpie`' && exit

	# elige una subidor al azar
	OPCION=`[ ! "$2" == "" ] && echo $2 || echo "uploadpie" | uno`
	# genera el archivo basado en el standar imput y le genera una extension
	if [ "$1" == "" ]; then
		f=`mktemp`
		cat /dev/stdin > $f
		# genera una extension para generar la tuberia
		EXT=`file -i $f | sed 's/^.*\/\(.*\);.*$/\1/g; s/\ //g'`
		mv $f "$f.$EXT"
		f="$f.$EXT"
	else
		f=$1
	fi
	# verificar si un gif, jpg, png tiene más de 3M subir a imgur

	# excepcion si es un txt (md, markdown) o pdf
	# cualquier archivo desconocido convertir en txt :P
	[ ! "$(echo $f | grep "\.\(png\|gif\|jpeg\|jpg\|pdf\|txt\)$")" ] && cp $f $f.txt && f=$f.txt

	# pdf: uploadpie
	[ "$(echo $f | grep "\.pdf$")" ] && OPCION=`echo "uploadpie" | uno`

	# txt: uploadpie o paste (3 de 4)
	[ "$(echo $f | grep "\.txt$")" ] && OPCION=`echo "paste paste paste uploadpie" | uno`

	# imgur (gif, png, jpg) se puso la gorra imgur
	#[ "$OPCION" == "imgur" ] && proxychains curl -F "file=@$f" http://imgur.com/upload \
	#| sed 's/^.*,"hash":"/http:\/\/imgur.com\//g; s/".*$//g'

	# uploadpie (3M gif, png, jpg, pdf & txt)
	[ "$OPCION" == "uploadpie" ] && proxychains curl -F upload=1 -F "uploadedfile=@$f" -F expire=5 -# http://uploadpie.com/ \
	| grep -o 'http://uploadpie.com/[^\" ]*' | grep http://uploadpie.com/...

	# principalmente para texto
	[ "$OPCION" == "paste" ] && proxychains wgetpaste -g -v -r -n "`nombre`" \
	-s `echo "bpaste codepad dpaste gists poundpython" | uno` $f \
	| grep -o "https\?://[^\"']\+" | tail -n 1

	# copado para mensajes cifrados y descifrar online
	[ "$OPCION" == "tinyurl" ] && cat $f | tinyurl

	# borra el archivo generado por bufandarosa
	[ -f "$1.txt" ] && borrar "$1.txt"
	[ "$1" == "" ] && borrar "$f"
}
function cifrar {
	[ "$1" == "-h" ]&& echo 'cifra mensajes, ejemplo `echo "hola" | cifrar clave`' && exit
	gpg -c --passphrase "$1" 2> /dev/null | base64 -w20 $2
}
function descifrar {
	[ "$1" == "-h" ]&& echo 'descifra mensajes, ejemplo `echo "hola" | cifrar clave | descifrar clave`' && exit
	tr "\n" " " | sed -e :a -e 's/<[^>]*>//g;/</N;//ba' \
	| sed 's/[^0-9A-Za-z=\/+-]//g' | base64 -d | gpg -d --passphrase "$1"
}
function l33t {
	tr 'A-Z' 'a-z' |\
	sed 'y/aeiotbs0gil/4310785O911/' |\
	tr 'a-z' 'A-Z'
}

function ofuscar {
	tr 'A-Z' 'a-z' |\
	sed 'y/abcdefghijklmnħopqrstuvwxyz1234567890/ɐß¢Ð€ƒ9ħ¡jĸ|MŋñøþqR§†µ^W×¥łı23456Ŧ89ø/'

}

function qr {
	[ "$1" == "-h" ]&& echo 'genera un qr con un mensaje, ejemplo `echo "hola" | cifrar 1234 | qr > imagen.png`' && exit
	f=`mktemp`
	cat /dev/stdin > $f
	qrencode "$f" -o -
	borrar "$f"
}

function viagra {
	[ "$1" == "-h" ]&& echo 'ofusca un mensaje usando pixel, ejemplo `echo "hola" | viagra > imagen.png`' && exit

	# fuente al azar
	FONT=`convert -list font | grep Font | cut -d":" -f2 | sed 's/\ //g' | uno`

	# genera el QR para hacer la publicidad de Bufanda
	# echo "Bufanda Rosa - http://br.sf.net" | qrencode  -i -s 1 -o /tmp/br.png

	# convierte el texto a imagen
	while [ 1 ]; do
		cat /dev/stdin | col -b | expand \
		| convert -size 750 \
		-pointsize $[$RANDOM%6+14] -font $FONT caption:@- \
		-distort Arc  $[$RANDOM%9] \
		-colors $[$RANDOM%10+8] \
		+noise Impulse \
		-delete 1--1 -quality 0 -bordercolor snow -border $[$RANDOM%7+3]x$[$RANDOM%7+3] \
		-threshold $[$RANDOM%20+60]% \
		-colors 2 \
		-strip \
		gif:- && break
	done

	exit

	# ---------- version animada ----------------
	cat /dev/stdin | col -b | expand \
	| convert \
	-size 750 \
	-pointsize $[$RANDOM%6+15] -font $FONT caption:@- \
	-distort Arc  $[$RANDOM%9] \
	-colors $[$RANDOM%10+8] \
	salida.png

	# convierte el texto a imagen
	for N in $(echo "1 2 3"); do
		convert salida.png \
		+noise Impulse \
		-threshold $[$RANDOM%5+60]% \
		-colors 2 \
		$N
	done
 	convert 1 2 3 -loop 0 final.gif
}
# ----------------------
function pixelar {
	[ "$1" == "-h" ]&& echo 'codificar un mensaje usando colores, ejemplo `echo "hola" | pixelar > imagen.png`' && exit
	# codificar
	COLORES=`cat /dev/stdin | gzip -c | base64 -w0`
	ELEMENTOS=`echo $(($(echo "$COLORES" | wc -c)/3))`
	# ELEMENTOS=`echo "sqrt($(echo $COLORES | wc -c)/3)" | bc -l | sed 's/\..*$//g'`
	echo -e "P6\n$ELEMENTOS 1\n255\n$COLORES" | convert ppm:- png:-
}

function despixelar {
	[ "$1" == "-h" ]&& echo 'descodificar colores, ejemplo `cat imagen | despixelar`' && exit
	# descodificar
	convert - -scale x1 ppm:- | sed -n '4,100p' | base64 -d 2> /dev/null | gzip -d
}
# ----------------------
function cifrar_irc {
	while read SALIDA; do
		if [ "$(echo $SALIDA | grep -i '^privmsg ')" ]; then
			A=`echo "$SALIDA" | sed 's/:.*$//g'`
			B=`echo "$SALIDA" | sed 's/^.*://g' | cifrar "$*" -w0`
			echo "$A:$B"
		else
			echo "$SALIDA"
		fi
	done
}

function descifrar_irc {
	while read SALIDA; do
		if [ "$(echo $SALIDA | grep -i ' privmsg ' | grep -v $'\x01')" ]; then
			A=`echo "$SALIDA" | sed 's/\ :.*$//g'`
			B=`echo "$SALIDA" | sed 's/^:.*\ ://g' | descifrar "$1"`
			# parche por que a veces anda mal
			[ "$B" == "" ] && echo "$SALIDA [sin cifrar]" || echo "$A :$B"
			echo "$SALIDA" > /dev/stderr
		else
			echo "$SALIDA"
		fi
	done
}

function sock {
	[ "$1" == "-h" ]&& echo 'conecta a un servidor usando SSL o sin él, ejemplo `sock servidor puerto`' && exit
	 gnutls-cli $1 --port $2 || nc $1 $2 || telnet $1 $2 || exit
}
function proxy {
	[ "$1" == "-h" ]&& echo 'levanta un proxy local, ejemplo `proxy puerto`' && exit
	nc -l 127.0.0.1 $1 || nc -l $1
}
function irc {
	[ "$1" == "-h" ]&& echo 'genera un proxy de un servidor de irc y cifra la conexion, ejemplo `irc irc.freenode.net 6697 clave 6667`' && exit
	# archivo fifo temporal
	MENSAJE="/tmp/$(pwgen -s -1 $[$RANDOM%10+6])"
	mkfifo $MENSAJE 2> /dev/null
	cat $MENSAJE | sock $1 $2 | descifrar_irc $3 | proxy $4 | cifrar_irc $2 > $MENSAJE
}
# http://www.imagemagick.org/Usage/transform/ mirar a este software
function desesteganografia {
	[ "$1" == "-h" ]&& echo 'muestra el mensaje dentro de una archivo o un QR, ejemplo desesteganografia clave imagen`' && exit
	# no se usa mas
	zbarimg --raw -q "$f" | descifrar "$1" || steghide extract -p "$1" -sf "$f" -xf - || cat "$2" | descifrar "$1"
}
function esteganografia {
	[ "$1" == "-h" ]&& echo 'guarda un mensaje dentro de una archivo, ejemplo `echo 'hola' | esteganografia clave imagen`' && exit
	# nombre del archivo
	f="$2"
	# si el formato no coincide lo convierte
	if [ ! "" == "$(file -i "$2" | grep -i "\/\(jpe\?g\|bmp\|wav\|au\)$")" ]; then
		# convierte imagen a jpg || convierte audio a wav
		if [ "" == "$(file -i "$2" | grep 'image/')" ]; then
			convert "$2" "$f.jpg"
			f="$f.jpg"
		else
			ffmpeg -i "$2" "$f.wav"
			f="$f.wav"
		fi
	fi
	# embebe el mensaje
	steghide embed -ef - -p "$1" -cf "$f"
}
# ---------------
function descarga {
	# me gustaria convertir esto en GET
	[ "$1" == "-h" ]&& echo 'descarga archivos con Tor, ejemplo `descarga http://loquesea.org`'  && exit
	proxychains wget --no-check-certificate "$1" "$2" -qO -
}
function basura {
	[ "$1" == "-h" ]&& echo "genera datos al azar" && exit
	basura=`pwgen -s -y 10000`
}
function ayuda {
	echo "Bufanda Rosa"
	echo "============"
	echo
	funciones="basura cifrar descarga descifrar nombre paste tinyurl uno irc sock pixelar despixelar"
	for N in $funciones; do
		echo " $N			`$N -h`"
	done
}
function alias {
	funciones="basura cifrar descarga descifrar nombre paste tinyurl uno irc sock pixelar despixelar"
	for X in $funciones; do
		echo "alias br_$X='echo $X | bufandarosa -c';"
	done
}
function progreso {
	echo "espere por favor"
	cat /dev/stdin
}
#---------------------- ejecuta linea de comandos -----------------

while getopts chiu OPCION; do
        case $OPCION in
	c)
		{ [ ! "$2" == "" ] && cat $2 || cat /dev/stdin; } \
		| while read LINEA; do
			eval $LINEA
		done

		exit
	;;
	u)
		NOMBRE=`basename $0`
		REPO="BufandaRosa"
		cd /tmp
		# unificar estas dos lineas
		wget -O master.zip https://github.com/b4zz4/$REPO/archive/master.zip
		unzip master.zip
		cd $REPO-master/
		chmod +x $NOMBRE
		./$NOMBRE -i && echo "actualizado"
		exit
	;;
	h)
		echo "$0 "
		echo
		echo "  -h Esta ayuda"
		echo "  -i Instalación"
		echo "  -u actualiza el programa"
		echo "  -c linea de comandos"
		echo '  `echo "ayuda" | bufandarosa` muestra ayuda sobre los comendos'
		exit
	;;
	i)
		NOMBRE=`basename $0`
		#echo "$NOMBRE no está instalado" | mostrar
		echo -e "[Desktop Entry]\nName=Bufanda Rosa\nDescription=No tengo nada que ocultar, pero sí mucho que proteger\nIcon=$NOMBRE\nType=Application\nExec=$NOMBRE\nCategories=GTK;Utility;" > /tmp/$NOMBRE.desktop
		# dependencias
		TMP=$(mktemp)

		# verifica el sistema operativo
		[ "$(which yum)" ] && aptitude="yum -y install" ||\
		[ "$(which pacman)" ] && aptitude="pacman -S" ||\
		aptitude="apt-get -y install"

		# permiso de superusuario
		[ "$(which su)" ]   && gksu="su -c"
		[ "$(which sudo)" ] && gksu="sudo"
		[ "$(which gksu)" ] && gksu="gksu"

		echo "$aptitude imagemagick
		$aptitude steghide
		$aptitude zenity
		$aptitude tor
		$aptitude xsel
		$aptitude proxychains
		$aptitude zbar-tools
		$aptitude qrencode
		$aptitude wgetpaste
		$aptitude gnutls-utils
		$aptitude gnutls-bin
		$aptitude netcat-openbsd || $aptitude gnu-netcat
		cp $NOMBRE /usr/bin/
		[ ! "$(which wgetpaste)" ] && cp wgetpaste /usr/bin/
		cp img/$NOMBRE.png /usr/share/pixmaps/
		cp /tmp/$NOMBRE.desktop /usr/share/applications/$NOMBRE.desktop" > $TMP
		echo "espera por favor"
		$gksu "bash $TMP" 2> /dev/null
		rm $TMP
		exit
		;;
	esac
done

#---------------------- funciones graficas -----------------
function opciones {
	while getopts t:m: OPCION; do
	        case $OPCION in
	                t) TITULO=${OPTARG}
	                ;;
	                m) MENSAJE=${OPTARG}
	                ;;
	        esac
	done
	# parametros
	N=0
	for T in $(cat /dev/stdin); do
		T=$(echo $T | sed 's/_/\ /g')
		C="$C $N \"$T\""
		N=$(($N+1))
	done
	# genera el menu
	eval "zenity --window-icon=/usr/share/pixmaps/bufandarosa.png --title \"$TITULO\" --text \"$MENSAJE\" --list --height=250 --column \"\" --column \"\" --hide-column 1  --hide-header $C"
}
function error {
	zenity --window-icon=/usr/share/pixmaps/bufandarosa.png  --error --text="$*"
}
function alerta {
	zenity --window-icon=/usr/share/pixmaps/bufandarosa.png  --warning --text="$(cat /dev/stdin)"
}
function clave {
	zenity --window-icon=/usr/share/pixmaps/bufandarosa.png  --title "Clave" --text "Introducir la clave" --entry --entry-text="$*"
}
function clave_gpg {
	zenity --window-icon=/usr/share/pixmaps/bufandarosa.png  --title "Clave" --text "Introducir la clave" --entry --entry-text="$*"
}
function url {
	zenity --window-icon=/usr/share/pixmaps/bufandarosa.png  --title "URL" --text "Dirección" --entry --entry-text="$*"
}
function archivo {
	zenity --window-icon=/usr/share/pixmaps/bufandarosa.png  --title "Elije el archivo" --file-selection
}
function archivos {
	echo -e "$(zenity --window-icon=/usr/share/pixmaps/bufandarosa.png  --title "Archivos" --text="Elije los archivos" --file-selection --multiple --separator="\n" \
	|| error "si necesita un archivo" && exit)"
}
function mensaje {
	zenity --window-icon=/usr/share/pixmaps/bufandarosa.png  --title "Mensaje" --text="Escribe el mensaje" --width=450 --height=350 --text-info --editable
}
function mostrar {
	# mensaje de entrada
	MENSAJE=`cat /dev/stdin`
	if [ "$(echo "$MENSAJE" | wc -l )" == "1" ]; then
		zenity --window-icon=/usr/share/pixmaps/bufandarosa.png  --title "Mensaje decifrado" --width=450 --text="$*" --entry --entry-text="$MENSAJE"
	else
		echo "$MENSAJE" | zenity --window-icon=/usr/share/pixmaps/bufandarosa.png  --title "Mensaje decifrado" --text="$*" --width=450 --height=350 --text-info
	fi
	echo "$MENSAJE" | xsel -i
}
function progreso {
	zenity --window-icon=/usr/share/pixmaps/bufandarosa.png  --progress --pulsate --auto-close --auto-kill &
	cat /dev/stdin
	killall `%1`
}

# -------------------------- programa ----------------------------------

# ¿Que queres hacer?
MENU=`echo  "Cifrar Descifrar Publicación_Anónima Mensaje_enrarecido IRC_cifrado Quitar_metadatos Eliminar_archivos Ayuda" | opciones -t "Bufanda Rosa" -m "¿Que queres hacer?"`

case $MENU in
	0 )
	# Cifrar
	#------------------ entrada ----------------------
	MENU=`echo -e "Escribir_mensaje Archivo" | opciones -t "Ciframe" -m "¿Que deseas proteger?"` || exit
	case $MENU in
		0 )	# escribir un mensaje
			ef=`mensaje`
		;;
		1 )	# elige un archivo
			ef=`cat $(archivo || exit)`
		;;
	esac
	k=`clave $(pwgen -s -y -1 $[$RANDOM%10+6])`
	MENU=`echo -e "Texto Imágen_o_Audio Imágen_al_azar_de_la_web Publicar_en_TinyURL Publicar Código_QR" | opciones -t "¿En donde?" -m "¿Donde lo queres ocultar?"` || exit
	case $MENU in
		0 )
		# genera el mensaje y lo muestra en base64
		echo "$ef" | cifrar "$k" -w80 | mostrar
		;;
		1 )
		# guardar en un archivo (propio)
		b=`archivo || exit`
		basura | esteganografia "$k" "$cf"
		# guarda nuestro mensaje
		echo "$ef" | esteganografia "$k" "$cf"
		;;
		2 )
		# busca una imagen al azar en la web (con tor)
		# descarga el RSS para buscar imagenes
		cd $PICTURES
		# genera el nombre del archivo
		cf="`nombre`.jpg"
		for W in {1...3}; do
			# fuentes RSS
			FUENTE=`echo -e "http://ycpi.api.flickr.com/services/feeds/photos_public.gne \
			http://www.nasa.gov/rss/lg_image_of_the_day.rss \
			http://backend.deviantart.com/rss.xml" | uno`
			# url de la imagen
			img_url=`descarga $FUENTE\
			| grep -o '<*\(enclosure\|media:content\)[^>].*>' \
			| grep -o 'http://[^\" ]*' | uno`
			# directorio de imagenes
			echo $img_url > /dev/stderr
			descarga "$img_url" | progreso > "$cf"
			if [ -f "$cf" ]; then
				break
			fi
		done | progreso
		if [ ! -f "$cf" ]; then
			error
			exit
		fi
		# agrega mucha basura
		basura | esteganografia "$k" "$b"
		# genera la imagen con password real
		echo "$ef" | esteganografia "$k" "$b"
		xdg-open "$(pwd)/$cf"
		echo "$(pwd)/$cf" | mostrar "Imágen con un secreto"
		publicar "$sf" | mostrar "URL de publicación"
		;;
		3 )
			# tinyurl
			# genera el mensaje y lo muestra en base64
			m=`echo "$ef" | cifrar "$k"  -w0`
			# si no se puede genera la tinyurl prueba varias veces
			u=` tinyurl "$m" | progreso || tinyurl "$m" | progreso || tinyurl "$m" | progreso || error "No se generó la tinyURL"`
			# muestra el archivo o mensaje cifrado
			echo $u | mostrar
		;;
		4 )
			# genera el mensaje, lo publica y lo muestra en base64
			echo "$ef" | cifrar "$k" | paste | progreso | mostrar
			exit
	   	;;
		5)
	                # genera codigo QR
			cd $PICTURES
			sf=`nombre`.png
			echo "$ef" | cifrar "$k" -w0 | qr > "$sf" || error "Los QR tienen espacio limitado :(" && exit
			metadatos "$sf"
			echo "$(pwd)/$sf" | mostrar "Código QR generado"
			publicar "$sf" | mostrar "URL de publicación"
	;;
	esac
	;;
	1)
	# Descifrar

	# mensaje archivo o URL
	MENU=`echo -e "Mensaje Archivo_o_Código_QR Dirección_web" | opciones -t "Descifrar" -m "¿Dónde queres buscar?"` || exit
	case $MENU in
		0 )
			# texto
			m=`mensaje`
			p=`clave`
			echo "$m" | descifrar "$p" | mostrar
			exit
		;;
		1 )
			# archivo
			sf=`archivo` || exit
		;;
		2 )
			URL=`url` || exit

			# archivo temporal
			sf=`mktemp`
			if [ "$(echo $URL | grep tinyurl)" ]; then
				# contenida en la URL
				echo "$(descarga "$URL" "-S" > /dev/null  2> /dev/stdout | grep "Location:" | cut -d, -f2)" > $sf
			else
				# crea un archivo temporal
				descarga "$URL" > $sf
			fi | progreso
			# mensaje descifrado en archivo
		;;
	esac

	# descifrado generico
	p=`clave`

	echo "`desesteganografia "$p" "$sf" | cat $sf | descifrar "$p"`" | mostrar
	borrar $sf 2> /dev/null

	;;
	2 )
		# publicacion anonima
		mensaje | paste | progreso | mostrar
	;;
	3 )
		# Mensaje enrarecido
		f="`mktemp`.gif"
		# publicacion anonima
		mensaje | viagra > $f || exit
		xdg-open $f
		echo $f | mostrar
	;;
	4 )
		# proxy IRC cifrado - basado en el concepto de dirtirc
		# elegis el servidor
		SERVIDOR=`url "irc.freenode.net 6697" ` || exit
		# clave
		p=`clave $(pwgen -s -y -1 $[$RANDOM%10+6])` || exit
		# puerto
		puerto=`url "6667"` || exit
		while [ 1 ]; do
			irc $SERVIDOR "$p" "$puerto" 2>&1| zenity  --window-icon=/usr/share/pixmaps/bufandarosa.png  --notification --listen
			# nota necesita icono
			sleep 1
		done
	;;
	5 )
		# Quitar metadatos
		archivos  || exit | while read ARCHIVO; do
			# falta quitar las caras
			# opcion para romper pixels
			metadatos "$ARCHIVO"
		done | progreso
	;;
	6 )
		# Eliminar archivos de modo seguro
		archivos || exit | while read ARCHIVO; do
			# borra el archivo para simpre
			borrar "$ARCHIVO"
		done | progreso
	;;
	7 )
		echo -e "# Bufanda Rosa\n_No tengo nada que ocultar, pero sí mucho que proteger_\n\nhttps://github.com/b4zz4/BufandaRosa" | mostrar
	;;
esac

exit

# Como funciona

- ¿Que queres hacer?

  1a. buscar mensaje
     1a. ¿campo de entrada para el mensaje?
     1b. ¿desde un archivo?
       a. buscar archivo
     1b. ¿desde una URL?
       a. Feed (busca descifra y se queda a la espera) con Tor
       b. Archivo lo descarga con Tor descifra y borra (de modo seguro)
     2. poner password
     3. mensaje descifrado

  1b. ¿Que queres ocultar?
     1a. Mensaje
       a. campo de entrada para el mensaje de texto
     1b. Archivo
       b. campo para elegir el archivo
     2. generar archivo con mensaje oculto
       1a. ¿elige un archivo?
         b. campo para elegir el archivo
       1b. ¿descarga una imagen o audio al azar?
       2. la modifica sustancialmente
       3. agrega el mensaje al archivo
     3a. Publicación
       4. publica de modo anonimo usando Tor
     3b. Guardar (sobre escribe el archivo)

## Quehaceres

- publicar en :
		# "http://www.cjb.net/"=>{"image"=>"____"},
   		# "http://kimag.es/"=>{"userfile1"=>"____"},
		# "http://tinypic.com/"=>{"the_file"=>$ARGV[0]}
